name: Deploy ARM template to Azure Data Factory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate ARM template
        uses: Azure/data-factory-validate-action@v1.1.5
        with:
          path: './'
          id: '/subscriptions/9159e293-4e60-412b-83bf-2db7438e23c9/resourceGroups/rg-datafact/providers/Microsoft.DataFactory/factories/dev-datafact-gs'
            
     

      - name: Export Azure Data Factory
        id: export
        uses: Azure/data-factory-export-action@v1.2.0
     
      
      - name: Publish ARM template
        uses: actions/upload-artifact@v4
        with:
          name: adf-armtemplate
          path: ${{ steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 
     
      - name: Download ARM template
        uses: actions/download-artifact@v3
        with:
          name: adf-armtemplate

      - name: Deploy resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }} 
          dataFactoryName: ${{ secrets.AZURE_DATA_FACTORY }} 
          # with:
          # subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}  # Target Resource Group
          # template: './arm-templates/ARMTemplateForFactory.json'  # ARM template file path
          # parameters: './arm-templates/ARMTemplateParametersForFactory.json'  # Parameters file path
          # deploymentName: 'adf-deployment'
